### ISSUE TITLE
Reply to mail

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#114]
We need a way to reply to an e-mail. It's currently half implemented without any tests. This looks more trivial than it actually is, since we need to create a quoted body of the replying mail. Also, keep this item to replying to the `from` header only.

**Comment by frasertweedale** [comment]
Or the `Reply-To` header.

**Comment by romanofski** [comment]
Dang! Good point! Didn't think of it...

**Comment by romanofski** [comment]
Since we're using purebred-email now, I think I'll finish this item.
