### ISSUE TITLE
Basic file browser widget needed for attachments (save, add, etc)

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#118]
We actually need some sort of a file browser in order to provide a way to attach files. I'm torn what a basic variant should look like: a simple list or a text editor with auto completion. The list seems quicker, although we need some kind of auto-completion text editor in the future ...

**Comment by romanofski** [comment]
I've now chosen a list representation as a start to browse the file system. I want to try out a multiple select when attaching files which will probably be useful for #5 as well.

**Comment by romanofski** [comment]
... but I'm stuck. I wanted to set the initial search path for the file browser by an IO action (`getHomeDirectory`) and set it to a `FilePath` during conversion to `InternalConfiguration`. I'm running right into the Lens problem again we've had when we implemented this idea:

```
   • Couldn't match type ‘a’ with ‘b’
      ‘a’ is a rigid type variable bound by
        the type signature for:
          confNotmuch :: forall a c b (f :: * -> *).
                         Functor f =>
                         (NotmuchSettings a -> f (NotmuchSettings b))
                         -> Configuration a c -> f (Configuration b c)
        at src/Types.hs:182:16
      ‘b’ is a rigid type variable bound by
        the type signature for:
          confNotmuch :: forall a c b (f :: * -> *).
                         Functor f =>
                         (NotmuchSettings a -> f (NotmuchSettings b))
                         -> Configuration a c -> f (Configuration b c)
        at src/Types.hs:182:16
      Expected type: (NotmuchSettings a -> f (NotmuchSettings b))
                     -> Configuration a c -> f (Configuration b c)
        Actual type: (NotmuchSettings b -> f (NotmuchSettings b))
                     -> Configuration b c -> f (Configuration b c)
    • In the expression:
        lens _confNotmuch (\ conf x -> conf {_confNotmuch = x})
      In an equation for ‘confNotmuch’:
          confNotmuch
            = lens _confNotmuch (\ conf x -> conf {_confNotmuch = x})
    • Relevant bindings include
        confNotmuch :: (NotmuchSettings a -> f (NotmuchSettings b))
                       -> Configuration a c -> f (Configuration b c)
          (bound at src/Types.hs:183:1)
```
but the next error is in Purebred.hs :/

I've pushed my current state to branch feature_file_browser: 5f50f41828486f4dcf8c2ce45bf22090dc7fa46b. @frasertweedale would you have time to have a look at this maybe?

**Comment by romanofski** [comment]
I continue with a hard coded path for now and leave it as a TODO ...

**Comment by frasertweedale** [comment]
Yeah I'll have a look at it... soon... keep prodding me until I do :)

**Comment by romanofski** [comment]
You had actually solved this problem for the `confNotmuch` lens, but I don't understand the solution. I'd be really interested in what the problem is and... well what the solution to it is then.

**Comment by frasertweedale** [comment]
Branch updated.  I modified the previous tip commit and added a couple of cleanup commits.

Here is the essence: for each new "abstract" field (i.e., one with an `IO Foo` version in `UserConfiguration` and plain old `Foo` in `InternalConfiguration`, we have to add a new type variable to `Configuration`.

So let's say we have
```haskell
data Configuration a
type UserConfiguration = Configuration (IO FilePath)
type InternalConfiguration = Configuration FilePath
```
and we want to add another `(IO FilePath)` field as in this commit.  We need to add another
type variable:
```haskell
data Configuration a b
type UserConfiguration = Configuration (IO FilePath) (IO FilePath)
type InternalConfiguration = Configuration FilePath FilePath
```

But in both `UserConfiguration` and `InternalConfiguration` the new type param is instantiated to the same type as an earlier type param!  So why do we still need the extra type var?

It's for `processConfig :: UserConfiguration -> IO InternalConfiguration`.  If we want to
use the optics, we can only do the conversion "step-wise", i.e. one field a time.  So
during the conversion we have to allow the types of the fields to vary.  That is, `processConfig`
"transitions through" some intermediate types:
```
1. Configuration (IO FilePath) (IO FilePath)  a.k.a UserConfiguration
2. Configuration    FilePath   (IO FilePath)  <-- not the same type anymore!
3. Configuration    FilePath       FilePath   a.k.a InternalConfiguration
```
And so on (extended to however many type vars we have... as of this commit it's 3).

**Comment by romanofski** [comment]
I see. I was wondering if we need a new type variable for a new field but dismissed it, because of being the same type. The transitioning makes sense tho. Will have a closer look at the changes. Thanks for the quick help. Much appreciated.

**Comment by romanofski** [comment]
I've realised that this task is a bit to big to be self contained. While I do have a file browser, the complexity of the mail composition view, renders this addition a bit useless. While technically it incorporates without problems, it will create a very confusing user experience which would have to be commented mostly with: "Yeah well, because it's not implemented yet...".

I've tried out the [Brick.Forms](https://hackage.haskell.org/package/brick-0.34/docs/Brick-Forms.html) module and I think that's the way to go with the view. For that to be incorporated smoothly however I need a few things, which I'll create as separate backlog items.

**Comment by romanofski** [comment]
I was working on this one before the refactoring. I think now it's time to get the shelved stuff out again and finish it.

**Comment by frasertweedale** [comment]
On Fri, Jun 22, 2018 at 10:48:11PM -0700, Roman Joost wrote:
> I was working on this one before the refactoring. I think now it's time to get the shelved stuff out again and finish it.
> 
Yeah, this is a pretty high priority in my books too.

**Comment by romanofski** [comment]
Lets close this and file new issues in case there is something in particular missing or needs changing.
