### ISSUE TITLE
Keep drafts in a secure directory

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#119]
As a make-work solution, the mail drafts are currently created in the systems temporary directory. That's not very secure and thinking ahead a bit, it's perhaps better to at least keep them in the users directory.

If we store them in the purebred config directory, or a directory configured by the user (e.g. call it drafts directory) the UI could be made so that users can easily pick drafts where they left off in order to send them (or discard).

So this backlog item is for:

a) add a config option to configure a directory to store drafts
b) change the action to use that directory
c) once we're here, file a new backlog item to build the UI for managing drafts

**Comment by frasertweedale** [comment]
Couple of notes:

Proper tmpfile creation will use the sticky bit and be user-readable only.  We should
see if `base` or some other foundational library has the appropriate functions to do this.
If not, it's an opportunity to add them.

But there is still the need for a *postpone* feature, where unsent mails can be persisted
even across program execution.  So it might make sense to avoid `/tmp` altogether.

**Comment by frasertweedale** [comment]
Item (c) can just use the mail view, with a list of mails loaded from the "drafts" directory.
This means we might need to abstract over the mail type i.e. `NotmuchMail` vs `FilesystemMail` or something like that.

**Comment by romanofski** [comment]
For c) another possibility I could think of is a mailbox and let notmuch index that as drafts. It does feel a bit over engineered tho, since I personally had never the demand to have to many drafts lying around that I had the need to index them. But just in case there are other benefits to have them indexed I can't think of, I'm mentioning it.

**Comment by frasertweedale** [comment]
@romanofski interesting suggestion.  So, that makes me think of another thing, and that is a "sent" folder.  Which is a things some users would want (I do!), and which you would want indexed.  With that in mind, if we do that, it probably does make sense to have a mail folder for drafts, within the notmuch mailstore, and indexed by notmuch... if only because it means we can reuse more code!

**Comment by romanofski** [comment]
To pick up on your comment, maybe this would also be a good item for a plugin?

**Comment by frasertweedale** [comment]
Not sure... it's a pretty baseline feature.  And we're allowed to be opinionated about *some* things, surely :)

**Comment by romanofski** [comment]
I guess it would suck not to be able to keep drafts somewhere if not in some mailbox, so perhaps keeping this for 1.0 would perhaps be nice.

**Comment by romanofski** [comment]
I've got a patch which creates (and removes) the drafts in a Maildir `Drafts` directory using maildir compliant file names. Having used what I implemented in #285 I realised that there is currently no way we can have a more fine grained error reporting system. For example, creating new directories (e.g. `Drafts`) or new files could fail for a myriad of reasons. At the moment I ignore the errors and fallback to a normal tempfile.

**Comment by romanofski** [comment]
Alright here is my approach for sending mail:

1. compose your mail
1. you want to postpone and purebred asks: discard or keep.
1. You keep. Purebred saves the mail in the notmuch maildir (mbox is currently not supported, sorry), tags it with a 'draft' tag. I'm currently thinking of really hardcoding the tag in purebred. You're back on the list of threads

For re-using the draft I'm thinking of implementing a new function/`Action` to basically write mails as new mails. Since we do need to support a list of "drafts", for now I thought it's "good enough" that you will have to search for `tag:drafts` and you use the `Action` to send as a new mail, which will bring your straight into the compose editor.

Any other ideas?

**Comment by romanofski** [comment]
Now thinking about this more, I'm tempted to postpone my previous comment in a separate card, but rather implement the indexing and keeping of "sent" mails. How does that sound?

This card will be just composing new mails which are stored in a drafts directory instead of the `$TEMPDIR`.

**Comment by romanofski** [comment]
Slept over it. I'll just implement it. Something is better than nothing.
