### ISSUE TITLE
Adding/removing tags on threads not doing what users expect them to do

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#121]
I've realised that the current tag operations changes labels on the mails in a different way than perhaps users would expect them. What happens is:

* add/remove operation is performed on a thread
* it then takes the tags and sets them to all messages in the thread

Example:
Thread 1 (inbox, unread, important)
* message 1 (inbox, unread)
* message 2 (inbox, important)

If a user now removes the tag `inbox`, adds the tag `archive`, all messages will end up being tagged as: archive, important, unread

That is because the `setNotmuchThreadTags` uses the tag list from the thread instead of taking each tag list for each message into account. This behaviour is perhaps correct for `setTags`, but it's certainly odd for adding and removing operations.

Expectation:
I think the expectation would be that adding tags on a thread, just adds the tag to the individual messages, while leaving the existing tags as is.

**Comment by frasertweedale** [comment]
I agree with the description of what `setNotmuchThreadTags` should do.
