### ISSUE TITLE
Simple version which build/version of purebred users are running

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#124]
I think purebred should have an option to see which version is running, in order to associate bug reports with a version.

Something like:
```
$ purebred --version
0.1.0.0 unreleased whatever
```
Hint: check for:
```Haskell
import Data.Version (showVersion)                                                              
import Paths_purebred (version) -- generated by cabal
```

**Comment by frasertweedale** [comment]
Good idea. Can show it in *help* view too, when the app is running.

**Comment by romanofski** [comment]
Actually for that won't we need an 'about' screen?

**Comment by frasertweedale** [comment]
/me shruggs.  Doesn't really matter.  Chuck it in the status bar for all I care right now :)

**Comment by romanofski** [comment]
Alright, whoever picks it can choose.

**Comment by romanofski** [comment]
Should perhaps include the hs-notmuch version introduced in purebred-mua/hs-notmuch#26

**Comment by frasertweedale** [comment]
@romanofski do we consider this done now?

**Comment by romanofski** [comment]
Yeah... suppose if we want to show the version in the UI we can add this a separate item.
