### ISSUE TITLE
Generate random e-mails for tests

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#125]
I think it would be beneficial to generate e-mails randomly for our tests. I currently haven't thought about any specifics and how it would work. Browsing [mime-mail](http://hackage.haskell.org/package/mime-mail-0.4.14/docs/Network-Mail-Mime.html) I think it has everything we'd need to generate an e-mail, write it to disk and let it get indexed by notmuch.

**Comment by frasertweedale** [comment]
@romanofski do we still want this, or are we happy with how we currently test the mail functions, including send?

**Comment by romanofski** [comment]
Nah still want it. Might not get to it for another... X years who knows, but I still like the idea.

**Comment by frasertweedale** [comment]
We have hedgehog generators for round-trip tests.  I think that ticks this box.  Adding additional tests (UAT or otherwise) that make use of this behaviour seems like it should be tracked separately, with more specific requirements.

Closing this issue.
