### ISSUE TITLE
Sending e-mail

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#13]
That's a bit of a *doh item, but very important to make it useful.

**Comment by frasertweedale** [comment]
Punt to local mailer for baseline?

Better idea: define a type for a mailer and configure the whole MUA with it.  Should be easy to refactor
later to use an MVar to *change* mailer, or support multiple mailers simultaneously, or whatever.

Interface would be something like...

```haskell
type Mailer = Mail -> IO MailerResult
data MailerResult = MailSent | MailNotSent MailerError
type MailerError = _ -- Something
```

**Comment by romanofski** [comment]
Oh actually I thought of only that. Just pass it on to sendmail ...

**Comment by romanofski** [comment]
Halfway through with this one. I think I can fix #3 in one go by fixing this one, due to the fact that we're keeping the necessary data for composing mail in the app state. I've already got a toggle working which allows to go back to the mail index during composition. In fact, this has potential as we could easily support composing multiple e-mails while switching back and forth to other views. Now, I'm on writing the little editor which allows to add attachments, change headers and so forth. I won't spend much time on details, since it's something we can flash out in smaller backlog items.

**Comment by frasertweedale** [comment]
:+1:

**Comment by romanofski** [comment]
Stumbled over [mime-mail](https://hackage.haskell.org/package/mime-mail-0.4.11) and think I'll use it for composition and sending mails. No opinion yet, just see how it goes...

**Comment by romanofski** [comment]
Sending plaintext e-mail is now implemented. I'll create another issue for composing multipart e-mail.
