### ISSUE TITLE
UI inconsistent for composing e-mail

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#139]
The current UI is empty, when the user starts composing an e-mail:

* when browsing threads press `m`. The input appears against a blank background for entering the `From` e-mail.
* when browsing an e-mail, the list of mails stays and the input appears which "looks" fine

The problem here is that the drawing code has no knowledge about the previous mode the user was in in order to draw most of the previous widgets and therefore a consistent UI. At the moment, the drawing code "hard codes" the list of mails as an accompanying UI element, but this obviously breaks down when the user looks at a list of threads.

Possible solutions:
a) Add more modes in order to express the additional UI elements which should be rendered to make the UI look consistent.
b) Keep track of what the previous mode was in order to decide what to draw with the widget.

**Comment by romanofski** [comment]
I've realised another instance where keeping track of previous modes would be handy: browsing files. Whether you want to add files as an attachment and return to the mail you're composing or saving attachments and go back to the list of mails depends on where you originated. Having access to some sort of bread crumbs would be crucial figuring out what view or mode to draw "next".

**Comment by frasertweedale** [comment]
basically we're getting close to stack-based window manager territory here :)

**Comment by romanofski** [comment]
Yeah I'm not keen to implement any window management routines albeit having had a few thoughts in that territory. Unless we can come up with a different approach than the current where a mode identifies one widget which receives all key bindings, I think there is no other way around than keeping track from which the mode the user came from.
Brick now features the ability to define [forms](https://hackage.haskell.org/package/brick-0.32.1/docs/Brick-Forms.html) which uses a focus ring to cycle between widgets which receive the key events. I was thinking of maybe using a similar approach to use one mode which renders a collection of widgets. That does not really address the particular problem (since you still don't know which previous mode a user was in in order to return there), but it would maybe make the creation of "views" more declarative. Perhaps a re-factoring for the future.

**Comment by romanofski** [comment]
I think with closing #173 this should be a thing of the past. We don't exactly if the current way of composing stays, but if so, we can sprinkle additional keybindings and modes throughout the code to make this better. At this point composing mails works from the list of threads and perhaps for a 1.0 release it's as good as it gets.
