### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#15]
Some issues had hinted on it, but we want to support this somehow. Not sure how an architecture would look like, but at least I think we need the item.

**Comment by romanofski** [comment]
Since GPG support is part of 1.0 and should be a plugin I'll set this also to needed for 1.0.

**Comment by frasertweedale** [comment]
With purebred-icu proving the concept, do we consider that there's anything substantive to do in general?  Of course, we will need to implement "hooks" for various features, but these will be addressed on a case-by-case basis. LMK what you think about closing this...

**Comment by romanofski** [comment]
The only question I have is: Do we just create new plugins or hook points as we see fit (e.g. implementing the GPG interoperability) or is it possible to draw an API up now?

**Comment by frasertweedale** [comment]
I don't think it's a good use of time, until we are actually focused on each use case.  At that point we can then ask "ok, so this is what we need for PGP, what other plugins need similar things?" and kind of think it through then.

**Comment by romanofski** [comment]
Sounds good!
