### ISSUE TITLE
White space in the subject header leads to weird UI artefacts

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#152]
This has been a problem for a while, but today I had time to look into. Some mails have newlines and tabs in their subject line, e.g.:
```
Subject: Long subject line with a newline and                                                    
  tab character in it ...
```
which notmuch is passing on. This leads to weird looking artefacts in the UI.

Currently there is no post processing of the subject line other than decoding. Maybe we need to strip the white space? It seems costly, but I'm not sure how costly it is.

**Comment by romanofski** [comment]
So a:

```Haskell
-- Storage.Notmuch line 212
(T.unwords . fmap T.strip . T.split isSpace . decodeLenient <$> Notmuch.threadSubject m)
```
does the trick, but it doesn't strike me as very efficient to do this on every subject.

**Comment by frasertweedale** [comment]
Use `T.filter` to strip all whitespace chars except `' '`?

**Comment by frasertweedale** [comment]
Also note that purebred-email does not have this issue with subjects.  It's an RFC822 thing and
*notmuch* appears to be cutting corners.

But the `filter` would be fine for now I think - it's a tradeoff between getting subj from notmuch -vs- parsing the mail using purebred-email and sucking the subj header out.
