### ISSUE TITLE
Move user acceptance tests into it's own repository?

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#156]
I'd like to open this issue to collect cases where a separate repository would be benefital for the user acceptance tests instead of currently being part of purebred.

**Comment by frasertweedale** [comment]
I don't see why it would be useful to separate the UAT into a different repository... why do you think it would be useful?

**Comment by romanofski** [comment]
More control over a specific (test-) environment. For example, I could setup the overall environment with a mail catcher and catch sent mails.
I know this feels all over engineered, but this issue is not to actually do it, but rather collect instances where such a thing would provide benefits over the current approach. If we there are more than enough, well maybe that's a reason to think about implementing it. If not, fine to close it.

**Comment by frasertweedale** [comment]
I'm gonna close this - I think we would always want the UAT to live in same repo.  If compelling reason to break it up emerges in future we can reopen or open a new ticket.
