### ISSUE TITLE
use dyre for configuration?

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#157]
The XMonad-style *program as configuration* approach is implemented in the [dyre](https://hackage.haskell.org/package/dyre) package.  It's used by a non-negligible number of other programs: http://packdeps.haskellers.com/reverse/dyre.

Perhaps we should use it too, and ditch our custom code?

**Comment by romanofski** [comment]
Yes. I think that's a good idea. Didn't know that it existed.
