### ISSUE TITLE
Parser needed for Text -> Network.Mail.Mime.Address

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#164]
We'll need a function/parser which can turn a `Text` into an [Address](https://hackage.haskell.org/package/mime-mail-0.4.11/docs/Network-Mail-Mime.html#t:Address). This is needed to close off #118

**Comment by romanofski** [comment]
Looking at: https://tools.ietf.org/html/rfc5322#section-3.4 I'm tempted to just implement a parser for the Addr-Spec Specification (3.4.1) only for now, unless this is useful even after with replace `Network.Mail.Mime`. The reason as to why I need the parser is to use it for validating the input, which arguably could also do a simple regexp (not 100% but close enough for now). @frasertweedale what are your thoughts?

**Comment by frasertweedale** [comment]
Yes, we need a proper datatype to represent these addresses and parsers / printers to match.
It should live in purebred-email.  Free free to tackle it.

My reading of RFC 5322 sect 3.4 suggests datatypes would be something like:
```haskell
data Mailbox = Mailbox
  (Maybe T.Text {-display-name-})
  B.ByteString{-addr-spec-}

data Address
  = Single Mailbox
  | Group T.Text{-display-name-} (NonEmpty Mailbox)
```

**Comment by romanofski** [comment]
Alright. I'll work on that next.

**Comment by romanofski** [comment]
I'm tempted to split the parser up in pieces to construct from `atom`, `dot-atom` and so forth. Is that ok? I've seen that you've done similar things with `atext` or special characters ...

**Comment by frasertweedale** [comment]
@romanofski yes, that is desirable; please implement in purebred-email though :)

**Comment by romanofski** [comment]
Yep yep. Easy.

**Comment by frasertweedale** [comment]
@romanofski have you started on this yet?  Got a WIP?  I have some long train travel tomorrow and could have a look at it or make a start myself.

**Comment by romanofski** [comment]
I started today and made progress. I've found one oddity parsing `atext`. See my branch at https://github.com/purebred-mua/purebred-email/tree/address_parsing which includes a failing test. When I look into it, using:

```Haskell
B.singleton <$> satisfy isAtext
```

seem to be consuming all the input, even for example: `,` should not satisfy and I would be expecting the parser to stop. Looking into `isAtext` there is no period specified and if I remove everything up to the asterisk (`*`) it parses correctly. So I wonder if the asterisk character is making it consume all input?

**Comment by romanofski** [comment]
Yeah I think `isAtext` should have the dash at the beginning instead of being intermixed with the rest of the characters looking at the [documentation](https://hackage.haskell.org/package/attoparsec-0.13.2.2/docs/Data-Attoparsec-ByteString.html#g:9).

**Comment by romanofski** [comment]
Alright, I think I've got the basic address parsing together, but will need more testing. I'm sure there are quite a few functions there which can be done better. Do you think this goes in the right direction? Anything I should be aware of when continuing (apart from maybe the obvious like documentation). I hope you've haven't picked this item for your train trip, since I was hacking the whole Sunday on it...

**Comment by romanofski** [comment]
A little bit more progress from me today. Got the `quotedPair` implemented as well. This is going to be slow ... :/
