### ISSUE TITLE
Thread's read state is not updated

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#167]
I've noticed that threads with a single mail will not update it's read state.

Steps to reproduce:
* select a thread which is unread with one mail
* view the mail which by default is set to read
* go back to the thread list

Actual results:
The mail is set to read (not bold) which is correct, but the thread itself is still shown as unread.

**Comment by romanofski** [comment]
I almost pushed a fix for this until realizing that it's more complex than I thought. When updating the read state of a mail in *a thread*, I can't just do the same *for the thread*. Reason being that the tags for the thread is just a set of all tags of all mails in the thread. Setting the thread to unread just because I've read one mail apart from **n** more, will lead to confusion. I'll need to think about this for a bit...

**Comment by frasertweedale** [comment]
On Thu, Feb 15, 2018 at 12:58:14AM +0000, Roman Joost wrote:
> I almost pushed a fix for this until realizing that it's more complex than I thought. When updating the read state of a mail in *a thread*, I can't just do the same *for the thread*. Reason being that the tags for the thread is just a set of all tags of all mails in the thread. Setting the thread to unread just because I've read one mail apart from **n** more, will lead to confusion. I'll need to think about this for a bit... 
> 
Can we just re-read the thread tags when activating thread view?

**Comment by romanofski** [comment]
@frasertweedale Yeah good idea. Might have a patch ready ...
