### ISSUE TITLE
Rendering HTML email

### ISSUE THREAD

**Issue by carlosdagos** [purebred-mua/purebred#174]
Hello! I've started using purebred and found out a lot of my email is in HTML. Is there currently a solution to rendering HTML email? Thanks!

**Comment by frasertweedale** [comment]
The initial support will be something like:

- support plugins that fire based on entity content-type
- add a plugin for piping the entity through an external program

Then you can configure 'text/html' bodies to be processed with 'lynx' or whatever
other program you'd like to use to format the HTML.

How does this sound to you?

**Comment by carlosdagos** [comment]
Sounds great! This is how I'd go about it myself. I'd love to contribute towards the initial support 😄

**Comment by frasertweedale** [comment]
OK cool.  Well so far I don't have anything particular in mind besides the design sketch above so feel free to hack something up, submit a pull request, and we can iterate from there.
