### ISSUE TITLE
"splash" screen

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#177]
if the initial search is very large, the program is unresponsive when starting up (nothing painted, looks like it's hung).

We should paint the UI first, possibly with a "loading" indication, while the initial search takes place.

**Comment by romanofski** [comment]
I always envisioned to use a progress bar for this. See: https://github.com/jtdaugherty/brick/blob/master/src/Brick/Widgets/ProgressBar.hs
I've never had a closer look about it's feasibility though. Suppose the loading of the mail's need some kind of callback...

**Comment by frasertweedale** [comment]
Yeah, maybe.  I don't think we need a progress bar.  Ideally even a huge search should be "fast enough", if we can find a way to load everything that is not on the initial screen either in the background, or lazily.

But even we do go for a progress bar, at least it will be a step forward to paint something and put a message saying "loading threads...", than what we currently have.

**Comment by frasertweedale** [comment]
Yeah, well I haven't landed the lazy vector stuff yet but I think it's safe to say we won't need this.
Closing.
