### ISSUE TITLE
Ways to edit attachments

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#182]
We need a way to view/edit attachments.

My initial thoughts were to add a parser for a mailcap file, but in 2018 perhaps there are better ways.

**Comment by romanofski** [comment]
After implementing #10, I think what would be useful to add in the configuration is a:

```Haskell
Map ContentType (ProcessConfig ()()())
```
Meaning, if we can lookup the ProcessConfig type (which supports `IsString`) by the given `ContentType` use it as a command, otherwise prompt the user.

Perhaps a Plugin could be later utilized which could for example parse an existing `mailcap` file and provide the `Map` ...

**Comment by romanofski** [comment]
I looked into this. The tricky bit could be `ProcessConfig` and using the above type, because we're getting into trouble with `NFData`:
```
src/Types.hs:348:24-29: error:
    • No instance for (NFData (ProcessConfig () () ()))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (NFData MailViewSettings)
    |
348 |     deriving (Generic, NFData)
    |                        ^^^^^^
```
It seems `ProcessConfig` is only exported as a type from the API which will make it harder for us to declare the `NFData` instance.

**Comment by frasertweedale** [comment]
@romanofski I think we want a richer type anyway - one that we can easily convert into a `ProcessConfig` - that allows more fine-grained control over where the filename appears, and supports pipes (perhaps).  For now I would say make the simplest data type that expresses what we currently support, create an `NFData` instance for it, and put that in the config.  Then we convert that to a `ProcessConfig` just in time to actually use it.

Alternatively, just make the `NFData` instance of the config record type that immediately includes the `ProcessConfig` values skip the `ProcessConfig` values.  It's not lawful, and not ideal, but there is precedent: see `instance NFData (Keybinding v ctx)` in `Types.hs` (there is no `NFData` instance for `Vty.Event` so I skip it.)

**Comment by romanofski** [comment]
I tried the latter, but that means I can pattern match on the `ProcessConfig` constructor, yes? Since the constructor is not exported I think I need to pick the first idea.

**Comment by frasertweedale** [comment]
@romanofski write the `NFData` instance for the thing that contains the `ProcessConfig`, and just don't `force` the `ProcessConfig` value.  There's no need to pattern match.

Push your WIP and let me help if you are unsure how to continue.

**Comment by romanofski** [comment]
Cheers! I'll try it out. I'll finish #263 off first since it's mostly mechanical work ...

**Comment by romanofski** [comment]
Will have to open this, since I filed this when I was hacking on listing attachments. I stumbled over a comment:
```Haskell
-- in src/UI/Actions.hs
        Nothing -> pure $ setError (GenericError "No file selected to edit") s
        Just (_, m) -> case preview (headers . contentDisposition . dispositionType) m of
          (Just Inline) -> invokeEditor' s
          _ -> pure $ setError (GenericError "Not implemented. See #182") s
```

Stumbling over this FIXME string actually reminded me of what #182 originally was intended when I filed it: The ability that the author of an e-mail can edit attachments on a newly composed email. We currently support only text/plain editing of the inline body, but this issue was intended that any attachment can be edited, saved and updated on composed mail.

**Comment by romanofski** [comment]
I'm thinking of adding an additional mailcap setting for editing attachments, e.g. 
```Haskell
data MailViewSettings = MailViewSettings
    {  -- [...]
    , _mvMailcap :: [(ContentType -> Bool, MailcapHandler)]
    }
```
to
```Haskell
data MailViewSettings = MailViewSettings
    {  -- [...]
    , _mvOpenMailcap :: [(ContentType -> Bool, MailcapHandler)]
    , _mvEditMailcap :: [(ContentType -> Bool, MailcapHandler)]
    }
```
and use `mvEditMailcap` for editing attachments **when composing** mails, while `mvOpenMailcap` is used to open attachments from received mails. Both can default to use `xdg-open` ...

**Comment by romanofski** [comment]
In the discussion for #318 we concluded to postpone this until we have a tree widget.  The card to close this off is #322
