### ISSUE TITLE
Viewing e-mails (needs a parser)

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#19]
While playing around, I've realised that viewing e-mails needs good support for a mime parsing library. Googling around seems to suggest that: https://hackage.haskell.org/package/mime is the one which might work well to parse mime contents. Any other suggestions?

**Comment by romanofski** [comment]
I'll spend some time on that...

**Comment by frasertweedale** [comment]
there are multiple levels here.

1. rfc2822 - the main email format.  this basically comes down to `(headers, body)`
2. body.  this is usually MIME but not always.  we should handle bodies that aren't MIME
    according to the content-type
3. MIME (multipart). Attachments, separate content types of parts, etc.

(4). pgp/mime et al - what we really want is a plugin interface to handle different MIME types, as discussed in other issues.

Anyhow lets see what you come up with :)

**Comment by romanofski** [comment]
Yeah I started into this with my ignorance just to show the mail with a body. With your comment realizing that was maybe a bit naive. Having said that my course of action would be this at this point:

* parse the e-mail using [mime](https://hackage.haskell.org/package/mime)
* pick the first content after parsing and display that

I'm currently uncertain if it makes sense to construct a new data type or simply use whatever the mime package provides. I think I currently stick with the mime data types.

Handling multipart, I envisioned to provide a separate view in the UI in which you can view, pipe, save and do whatever with the items. Maybe that part is better tracked by a separate issue however. I do think providing viewing and editing capabilities is something we need for a first version.

I'm not sure what I do about rfc2822 mails at this point if they're not supported by mime. Haven't tested it  however. Since a good chunk of mails is coming in as MIME, maybe it is something we can defer?

**Comment by frasertweedale** [comment]
On Thu, Jul 27, 2017 at 03:43:25AM +0000, Roman Joost wrote:
> I'm not sure what I do about rfc2822 mails at this point if
> they're not supported by mime. Haven't tested it  however. Since a
> good chunk of mails is coming in as MIME, maybe it is something we
> can defer?
> 
Maybe.  I need to think more on the approach.

**Comment by frasertweedale** [comment]
*mime* package looks alright.  A couple things I don't like:

- no optics (we can write our own of course)
- exposes content in its transfer-encoding (ideally it would expose the
  decoded value).
- `decodeBody :: String -> String -> String` yuck!  Takes a string arg for transfer encoding,
  and result type does not reflect the fact that this encoding (i.e. base64 or QP) can fail!
- all the decoding routines are rather Stringy.

Also checkout the Github issues (apparently QP decoding is broken somehow?):
https://github.com/GaloisInc/mime/issues

Let's go ahead and use it for now.  It should be fairly easy to replace down the track if we need to.

There is also the question of rfc822 parsing.  IMO we can leave this discussion focused on
MIME and I'll open a separate issue for rfc822 parsing.

**Comment by romanofski** [comment]
I second your thoughts on the library, although there is nothing better available at the moment. Maybe there is time and we can shoot some pull requests to improve it.

I've ended up with a data type for representing the Mail in the UI when a user chooses to view it:

```Haskell
  data ParsedMail = MIMEMail MIMEValue | RFC2822 [Header] Body
```
since I realised that we'll probably need somehow an abstraction over the parsing library to represent parsed mails in the UI. From my n00b point of view I don't know if that works well, so I just try and see how well it plays out. Obviously the RFC2822 constructor is currently just a placeholder and `Header` and `Body` just type aliases for `Text`.

**Comment by frasertweedale** [comment]
@romanofski does `parseMIMEMessage` successfully parse an RFC 822 message already?
On closer look maybe it does.  (But I have not tried it).

**Comment by romanofski** [comment]
Have not tested it yet. Will report back once I did.

**Comment by romanofski** [comment]
I can view mails now, but ... I think the parser is really slow if there is a motherlode of headers in the mail. It could also be that the rendering is really slow the way I assemble all (text-) widgets, so I'm not sure where the problem lies. I see if I can profile and see if it's the [mime](https://github.com/GaloisInc/mime/blob/master/Codec/MIME/Parse.hs#L105) parser, me picking the wrong function or screwing something else up.

**Comment by romanofski** [comment]
Abysmal. I've tried one of the pull requests (using `Data.Text.Internal.Builder`) which gives some relief, but subjectively it's still way behind from Pythons email parser. The profiling data is here if you'd like to have a look: [purebred.txt](https://github.com/purebred-mua/purebred/files/1182712/purebred.txt). I guess it's possible to concentrate on the UI and experiment with the proper rendering short term, but in the long run the module at is current state is no good. How do you feel about maintaining an email parser library ;)

**Comment by frasertweedale** [comment]
On Fri, Jul 28, 2017 at 10:28:30AM +0000, Roman Joost wrote:
> Abysmal. I've tried one of the pull requests (using
> `Data.Text.Internal.Builder`) which gives some relief, but
> subjectively it's still way behind from Pythons email parser. The
> profiling data is here if you'd like to have a look:
> [purebred.txt](https://github.com/purebred-mua/purebred/files/1182712/purebred.txt).
> I guess it's possible to concentrate on the UI and experiment with
> the proper rendering short term, but in the long run the module at
> is current state is no good. How do you feel about maintaining an
> email parser library ;)
> 
It's work I wish we didn't have to do. (But I will if necessary.)

How bad is it in reality, for an interactive program, if we can
defer parsing to when the email is viewed?  i.e. what is the worst
case you've seen for parsing a single message?

**Comment by romanofski** [comment]
We already defer parsing until necessary: when the user decides to view the mail. For some of them parsing is noticible. From the time you but enter until showing it takes perhaps a split second instead of an instand.
I wouldn't say it's unusable, but just not something you'd probably put up with on the long run. Note: all this with the pull requests for better performance applied. Without it, I think it is unusable.

PS: I think I'll take a timeout to focus the last days on my exam and be back afterwards.

**Comment by frasertweedale** [comment]
On Fri, Jul 28, 2017 at 02:22:20PM -0700, Roman Joost wrote:
> We already defer parsing until necessary: when the user decides to view the mail. For some of them parsing is noticible. From the time you but enter until showing it takes perhaps a split second instead of an instand.
> I wouldn't say it's unusable, but just not something you'd probably put up with on the long run. Note: all this with the pull requests for better performance applied. Without it, I think it is unusable.
> 
> PS: I think I'll take a timeout to focus the last days on my exam and be back afterwards.
> 
Yes, good idea.

I'll start pushing forward on rfc822 and MIME parsers.  I'll make
them a separate lib (possibly two libs, but we'll see).

Cheers,
Fraser

**Comment by frasertweedale** [comment]
@romanofski https://github.com/purebred-mua/purebred-email

No parser yet.  Will be using attoparsec, though.

**Comment by romanofski** [comment]
Since this issue is really broad I'd like to propose the following:
* Merge 02c4685 and closing this issue since it gives us rudimental viewing functionality
* Create separate, more fine grained items concerning viewing of emails.
* Continue on basic composing functionality

My idea is to have an early prototype we can start using and work on the remaining pieces for 1.0. What do you think?

**Comment by frasertweedale** [comment]
On Mon, Jul 31, 2017 at 03:41:10AM -0700, Roman Joost wrote:
> Since this issue is really broad I'd like to propose the following:
> * Merge 02c4685 and closing this issue since it gives us rudimental viewing functionality
> * Create separate, more fine grained items concerning viewing of emails.
> * Continue on basic composing functionality
> 
> My idea is to have an early prototype we can start using and work
> on the remaining pieces for 1.0. What do you think?
>
All fine with me.
