### ISSUE TITLE
mail send command should return a proper error type

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#200]
With fixing #196 we introduced a new command for sending mail with the type signature:

```Haskell
B.ByteString -> IO String
```
It is used to take the serialised mail and invoke the `sendmail` command for it. The `String` value is a poor man's way of indicating an error.

This should be refactored and a proper error type used:
```Haskell
IO (Either e ())
```
The `e` can be a `String` here, but possibly better is to define a new `Error` constructor.

**Comment by frasertweedale** [comment]
Ultimately, sending mail should have a plugin interface so folks can send mail via SMTP or whatever.
