### ISSUE TITLE
Replace System.Process with System.Process.Typed

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#201]
We should evaluate replacing the current use of `System.Process` with `System.Process.Typed` from http://hackage.haskell.org/package/typed-process-0.2.3.0/docs/System-Process-Typed.html

See discussion on #196

**Comment by frasertweedale** [comment]
This was done for UAT in https://github.com/purebred-mua/purebred/commit/078db1de275fa0026738f579af3b54da02606f4d.

**Comment by frasertweedale** [comment]
Nooope, we still got a bunch of other places to update it :)

**Comment by romanofski** [comment]
Ah sorry.. yes! of course.. the main program...
