### ISSUE TITLE
Purebred should select last e-mail in a thread if all mails are read

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#205]
If all mails are read, Purebred currently selects the first mail in a thread. Ideally when going back to a conversation, you want to check the last recent mail.

**Comment by frasertweedale** [comment]
Should be configurable via actions right.  listMoveToEnd or whatever?  Then the user can override it to get the behaviour they want.

**Comment by romanofski** [comment]
Hmmm... *doh? Why haven't I thought this earlier? Will check and report back.

**Comment by romanofski** [comment]
Hm... the tricky thing is that it depends on the "read" state of the mail. The key bindings currently don't have a to the list item (hm not sure if they should). At the moment the default is to pick the next unread which works well. I guess if all are read, just pick the last mail in a thread.
