### ISSUE TITLE
depend on lens

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#23]
Microlens docs say:

> don't use this library if:    You need Isos, Prisms, indexed traversals, or actually anything else which isn't defined here

We need those things.  Therefore depend on *lens*.

If we stick with *brick*, *microlens* will be a transitive dependency.  Oh well.

**Comment by romanofski** [comment]
Totally missed this. I picked microlens because I saw it in use by brick. However, it should be straight forward to simply change the dependency. Let me merge my viewing mails patch and I'll pick this one up too.
