### ISSUE TITLE
lazily load search results

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#233]
**Is your feature request related to a problem? Please describe.**
If search result is very long, it takes a long time to load all the items.

**Describe the solution you'd like**
List items should be progressively loaded as I scroll through the list.

**Describe alternatives you've considered**
There is no obvious alternative, besides doing nothing and enduring long pauses.

**Additional context**
Work is required in hs-notmuch as well.

**Comment by frasertweedale** [comment]
Filing this issue for a place to dump info about progress or issues as I encounter them.  First issue: lockups.  See `strace` output:

```
...
openat(AT_FDCWD, "/home/ftweedal/mail.bak/.lists.rhcs-dev-list/cur/1545169680.M286283P1100V000000000000FD03I000000000088733D_0.T470s,S=3725:2,S", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 40
fstat(40, {st_mode=S_IFREG|0600, st_size=3725, ...}) = 0
ioctl(40, TCGETS, 0x7ffcee47a780)       = -1 ENOTTY (Inappropriate ioctl for device)
fstat(40, {st_mode=S_IFREG|0600, st_size=3725, ...}) = 0
read(40, "Return-Path: rhcs-dev-list-bounc"..., 8192) = 3725
read(40, "", 8192)                      = 0
close(40)                               = 0
rt_sigprocmask(SIG_BLOCK, [INT CONT WINCH], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=0, tv_nsec=848623874}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [INT CONT WINCH], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=0, tv_nsec=849945670}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [INT CONT WINCH], [], 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=0, tv_nsec=851731850}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7f8c2c000ba8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f8c2c000bb0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x29273ec, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x29273f0, FUTEX_WAKE_PRIVATE, 1) = 0
stat("/home/ftweedal/mail.bak/.notmuch", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/ftweedal/mail.bak/.notmuch/xapian", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/ftweedal/mail.bak/.notmuch/xapian/iamchert", {st_mode=S_IFREG|0644, st_size=28, ...}) = 0
stat("/home/ftweedal/mail.bak/.notmuch/xapian/record.DB", {st_mode=S_IFREG|0644, st_size=5406720, ...}) = 0
stat("/home/ftweedal/mail.bak/.notmuch/xapian/record.baseA", {st_mode=S_IFREG|0664, st_size=103, ...}) = 0
stat("/home/ftweedal/mail.bak/.notmuch/xapian/postlist.DB", {st_mode=S_IFREG|0644, st_size=706560000, ...}) = 0
stat("/home/ftweedal/mail.bak/.notmuch/xapian/postlist.baseA", {st_mode=S_IFREG|0664, st_size=10802, ...}) = 0
openat(AT_FDCWD, "/home/ftweedal/mail.bak/.notmuch/xapian/flintlock", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 40
fcntl(40, F_OFD_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=1}
```

Seems that purebred is trying to acquire a write lock on the database.  This blocks, and the whole program locks up.  Possible solutions or things to investigate

- `unsafe` all the FFI methods and see if that dispels the issue (blocked FFI thread in `unsafe` call could be blocking whole runtime)
- promptly close the database when performing write operations.

**Comment by romanofski** [comment]
Hey.. that reminds me about my previous mail setup. I used mutt with the notmuch integration and offlineimap syncing my mail. Since both programs at times tried to use notmuch, the mutt integration ran into locking issues with xapian too. The reason I know this is, because of the STDERR output in mutt cluttering the UI, because it (re-)tried to acquire the lock. What part of the integration was responsible (whether notmuch lib or mutt) I don't remember, but I do remember the STDERR output. 

So while not great, I guess while we're throwing ideas around you could also retry a few times to write?

**Comment by frasertweedale** [comment]
@romanofski it's all good, I was at the wrong commit of hs-notmuch :/
