### ISSUE TITLE
RFC 822 mail parser

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#24]
We discuss requirements and options for MIME parsing at https://github.com/purebred-mua/purebred/issues/19.

But we also need to parse RFC (2)822 messages, where most of the headers life.
Conceptually, the type is `([Header], Body)`.

But note https://tools.ietf.org/html/rfc5322#page-21 ; some headers must appear
exactly once, zero or 1 times, or 0 or more times, and some headers have special
formatting.  We should expose this structure with optics (whether or not
the underlying representation has this structure).

IMO we should make a strict implementation of the standard, then parse
*a lot* of mail to find any counterexamples.  If it's a true counterexample and
not a bug in the parser, I'd like to NOT relax the parser implementation; instead,
we could implement "repairer functions" for working around common deficiencies.

Although if e.g. gmail produces non-conformant messages, well, maybe that will
be a case to relax the parser.

**Comment by romanofski** [comment]
Assigning this to you since you're currently working on this in purebred-mua/purebred-email

**Comment by frasertweedale** [comment]
This is partly resolved by the switch to purebred-email (https://github.com/purebred-mua/purebred/pull/136).

At this point I'd like to close it and any further work can be raised as separate issues.

**Comment by romanofski** [comment]
Absolutely 👍
