### ISSUE TITLE
nix build improvements

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#243]
A summary of what I'd like to achieve with the nix build.  All up for discussion.  I'm super n00b at nix so my ideas could be bogus.

- make the nixpkgs an optional argument (defaulting to `<nixpkgs>`) so that it is easy to e.g. build with unstable.

- use the default ghc from nixpkgs (whatever nixpkgs is being used, that is), by default

  - whether it is possible to override the default, I am ambivalent about, but it probably makes sense to have the option if only for test purposes

**Comment by romanofski** [comment]
Given by what I saw, both seem to be normal practices. Do you think it would be beneficial to change our travis job to either use 'nix' as the default language and build through nix or perhaps introduce a build job in order to test this?
