### ISSUE TITLE
Replace `selectedItemHelper` with over and L.listModify

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#258]
**Describe the bug**
I've realised that the `selectedItemHelper` helper function is superfluous, since we could simply replace it with calls using `over` and `Brick.

**To Reproduce**
Simple refactoring task, nothing to reproduce.

**Comment by romanofski** [comment]
Now coming back to this one and I have no idea what I meant. Perhaps Markdown throwing away half of the issue doens't help really. The `selectedItemHelper` function applies the given function, but also sets an error if in case nothing is selected. I would now how to manipulate the case in which an item is selected with `over`, but have no clue what I thought I'd do about the error case.

I think about it some more, but most likely close this one.

**Comment by frasertweedale** [comment]
Yep, closing.
