### ISSUE TITLE
Navigate between threads

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#261]
**Is your feature request related to a problem? Please describe.**
If you get a lot of single mails which show up as single threads, it's really hard to move in between them. You press `Enter` to see the mail, two key strokes `q` to get back to the thread list and `Enter` again to see the next.

**Describe the solution you'd like**
I would like to go up or down the thread list by a single key stroke.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
None

**Comment by frasertweedale** [comment]
Maybe we want a tree view where threads can be expanded/collapsed and messages opened/closed, instead of two separate views?  Just an idea.

**Comment by romanofski** [comment]
Yes we want a tree view, but the need still applies. I still want to move between threads, whether I update the tree view or view the current unread mail in the next thread.
