### ISSUE TITLE
replace tabs with spaces to fix rendering glitches

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#265]
**Describe the bug**
When message body contains tab characters, brick rendering glitches can occur (due to mismatch of brick's assumed line width based on number of characters, versus what the terminal actually does with tab characters).

**To Reproduce**
Open an email with tabbage.  Observe UI glitches.  Reproducer: https://frase.id.au/purebred-265-reproducer.eml

**Expected behavior**
No UI glitches.

**Screenshots**
Maybe later...

**Additional context**
Brick documentation is quite clear that, for the `str` and `txt` widgets, the **caller** must replace tabs with spaces.  See http://hackage.haskell.org/package/brick-0.47/docs/Brick-Widgets-Core.html#v:txt.

**Comment by romanofski** [comment]
Ah yes thank you! I kept forgetting to file this bug.
