### ISSUE TITLE
Support for keybindings

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#27]
We need support for mappings between a key press and a action. This should include redefining how to quit the program.

**Comment by romanofski** [comment]
I'm currently playing around with the following data type:

```Haskell
data Keybinding = Keybinding
    { _kbDescription :: String
    , _kbEvent :: Vty.Event
    , _kbAction :: AppState -> EventM Name (Next AppState)
    }
```
Then define all keybindings in a list and look up incoming keyboard events for the given Vty.Event. If it matches perform the action, if it doesn't... well perform a default action. I think that mostly comes down to `continue`.

Those are not configurable by a config file, but it's a first step.

**Comment by frasertweedale** [comment]
On Thu, Aug 03, 2017 at 05:14:12AM +0000, Roman Joost wrote:
> I'm currently playing around with the following data type:
> 
> ```Haskell
> data Keybinding = Keybinding
>     { _kbDescription :: String
>     , _kbEvent :: Vty.Event
>     , _kbAction :: AppState -> EventM Name (Next AppState)
>     }
> ```
> Then define all keybindings in a list and look up incoming keyboard events for the given Vty.Event. If it matches perform the action, if it doesn't... well perform a default action. I think that mostly comes down to `continue`.
> 
> Those are not configurable by a config file, but it's a first step.
> 
I leave these details for you for now @romanofski.

One thing to consider though... in future we might want to have
"chords" e.g. "ESC followed by p" and such.  So might be good to
think about how you could accommodate that in the type.

If you don't see an obvious way don't worry about it for now; we
can come back to it later.

**Comment by romanofski** [comment]
I hear ya... hm.. not sure how I would model that. I'll defer that. I also had in mind the support for uh macros? It's all a bit hand waiving, but I guess something in which you can apply a couple of functions on something... not sure.

**Comment by romanofski** [comment]
I've transformed most of the keybindings now and left alone the ones which are already handled by the widgets. I'm getting a bit worried with the lack of testing, but tell myself we can still add that once the interfaces are more stable.
