### ISSUE TITLE
year not shown on old mails

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#278]
**Describe the bug**
When reading an old mail (or in the thread list) the actual date/time/year of the mail is not shown.

**Expected behavior**

- Full date/time information should be shown in default headers.
- For threads > 1y old, year should be shown in date field of thread list.

**Comment by romanofski** [comment]
Yeah true. Not that there is room for it.

**Comment by frasertweedale** [comment]
@romanofski maybe `DD Mon` for mail < 1y old, and `Mon YY` for > 1y?

**Comment by romanofski** [comment]
Yeah sounds fine. I wonder if it's alright to not align it, so that an addional year pushes the rest to the right.

**Comment by frasertweedale** [comment]
How do you mean?  `DD Mon` and `Mon YY` are the same width anyway...

**Comment by romanofski** [comment]
Ah darn. Yes indeed! Never mind!
