### ISSUE TITLE
Be able to view current mails, while composing new mails

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#3]
In mutt it was always a pain if you needed to lookup details for a mail you're replying.

The workarounds ranged from either starting a new instance to lookup important details or postpone the mail, lookup the detail and continue.

Alternatively, when replying you should have access to the details of the mail you're replying to.

**Comment by frasertweedale** [comment]
I think we definitely want to be able to context-switch.  Merely having access to the
mail being replied-to is not enough.  (Same for not replying but starting new emails;  you
might still want to be able to reference other emails).

**Comment by romanofski** [comment]
Aaah yes. The last use case is a good one which gave me a few headaches before.

**Comment by frasertweedale** [comment]
Looking ahead, the possibility of tiling multiple views is there, but I think the "switch whole view"
approach is a satisfactory baseline (i.e. it is essentially what we currently do in mutt by
postpone/look-at-other-emails/resume, but promoted to a well supported workflow).

**Comment by romanofski** [comment]
Yes. The alot mail client is following an approach similar to vim, which basically creates buffers for every view (the index is a buffer, every mail view is a buffer) and you can switch between them with a keystroke. I think that's maybe a bit too much, since then you need to close every open buffer. But switching between index and composition via keystroke is perhaps a good middle ground?

**Comment by frasertweedale** [comment]
On Wed, Jul 19, 2017 at 12:40:17AM +0000, Roman Joost wrote:
> Yes. The alot mail client is following an approach similar to vim, which basically creates buffers for every view (the index is a buffer, every mail view is a buffer) and you can switch between them with a keystroke. I think that's maybe a bit too much, since then you need to close every open buffer. But switching between index and composition via keystroke is perhaps a good middle ground?
>
Let's determine details later.  We know what the requirement is; how
much further we go can be deferred to implementation time.

**Comment by romanofski** [comment]
Is this a baseline feature tho? I would think not... more a nice to have?

**Comment by frasertweedale** [comment]
On Wed, Jul 19, 2017 at 01:01:22AM +0000, Roman Joost wrote:
> Is this a baseline feature tho? I would think not... more a nice to have?
>
Up to you.

**Comment by romanofski** [comment]
Lets keep it at a nice to have for now, but if it turns out to be an easy fix ... why not.

**Comment by romanofski** [comment]
This came almost for free when implementing #13 since we're keeping the state of the currently composed e-mail and allow to switch back to the index. So I'm closing this one for now.
