### ISSUE TITLE
Provide a notmuch configuration parser for opening the database

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#31]
Currently the user needs to explicitly point purebred to the notmuch database, e.g.::

  purebred --database ~/Maildir

This is cumbersome. I've already configured notmuch with a path to the database. Purebred should parse the notmuch config and use the filepath configured in there.

**Comment by romanofski** [comment]
Seems the notmuch-config file is using [ini style](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html), so I suppose I'm grabing an ini parser.

**Comment by frasertweedale** [comment]
On Wed, Aug 09, 2017 at 04:49:21AM +0000, Roman Joost wrote:
> Seems the notmuch-config file is using [ini
> style](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html),
> so I suppose I'm grabing an ini parser.
>
Why not just invoke `notmuch config get database.path` ?  No ini
parser necessary.

**Comment by romanofski** [comment]
Darn... of course. Why haven't I thought of that earlier.

**Comment by romanofski** [comment]
No parser needed.
