### ISSUE TITLE
User Acceptance tests blocking forever in CI

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#321]
**Describe the bug**
I've now run into this twice hence filing this bug. Travis errors out with:

```

travis_time:start:0245bd55
$ if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} ${BENCH} all; fi
Build profile: -w ghc-8.6.3 -O1
In order, the following will be built (use -v for more details):
 - purebred-0.1.0.0 (test:uat) (ephemeral targets)
 - purebred-0.1.0.0 (test:unit) (ephemeral targets)
Preprocessing test suite 'uat' for purebred-0.1.0.0..
Building test suite 'uat' for purebred-0.1.0.0..
Running 1 test suites...
Test suite uat: RUNNING...


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

**To Reproduce**
Unable to reproduce

**Expected behavior**
user acceptance tests run

**Additional context**
I currently don't have a theory.

**Comment by frasertweedale** [comment]
Does it occur randomly or can it be reproduced reliably somehow?

**Comment by romanofski** [comment]
Nah it's random and seems to be rare. When I first saw it I thought it might be the CI. I still think it's the CI, but since it happened a second time I'm not so sure any more.

**Comment by romanofski** [comment]
Hm... we're using `cabal new-test` which, the last time I read the docs, doesn't automatically stream the results, but rather runs all tests and then shows the output. Could it be that an (output) buffer is full and therefore the entire thing hangs?

**Comment by frasertweedale** [comment]
You might be onto something...

**Comment by romanofski** [comment]
Happened here again: https://travis-ci.org/purebred-mua/purebred/jobs/614460305?utm_medium=notification&utm_source=github_status

**Comment by romanofski** [comment]
Happened today again: https://travis-ci.org/purebred-mua/purebred/jobs/647519028?utm_medium=notification&utm_source=github_status

**Comment by romanofski** [comment]
Happened again: https://travis-ci.org/github/purebred-mua/purebred/jobs/684070671

**Comment by romanofski** [comment]
Interesting failure I found with the GHC-8.6.5 test: 
[log.txt](https://github.com/purebred-mua/purebred/files/4655723/log.txt)

It's the same problem, yet the output is a bit different to the initial description.

**Comment by frasertweedale** [comment]
@romanofski given we moved from Travis, should we close this?

**Comment by romanofski** [comment]
Sure.. can always re-open if it happens again.
