### ISSUE TITLE
Error message can mess up the terminal

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#336]
**Describe the bug**
If the editor process hangs and is killed, the displayed error message can mess up the terminal (I presume).

**To Reproduce**
1. Start editing an email until you're dropped into your editor (e.g. vim)
2. Externally kill the `vim` process.
3. The compose editor now displays the error message.
4. It should be difficult to answer the confirmation dialog in order keep/discard the draft (`Enter` doesn't seem to work)

**Expected behavior**
Displaying the error message is fine (even though it's a wall of text), but the error message needs the same treatment we've introduced with any form of output to avoid messing with the terminal. See `Purebred.Types.IFC`.

**Additional context**
I'm not sure if the error message really is the culprit, but I thought I'd better file it in order to look into this issue.

**Comment by romanofski** [comment]
I looked into this briefly today and I have my doubts whether this is caused showing the error message or output from the process. I removed showing anything at all (other than, well there was an error) and still had trouble with the key input. Also after quitting purebred, the terminal was b0rked until a `reset` too.

**Comment by romanofski** [comment]
Made some progress here. The terminal settings after I kill vim, look like this:
```
$  stty
speed 38400 baud; line = 0; min = 1; time = 0;
-icrnl -onlcr -isig -icanon -iexten -echo -echoe
```
which is resulting in this weird terminal behaviour. In comparison my normal terminal settings after I ran a `reset`:

```
$ stty
speed 38400 baud; line = 0;
-brkint -imaxbel
```

I'll have to dig when where vim set's the terminal back to it's original state. I presume if the editor dies, that clean up isn't happening.

**Comment by romanofski** [comment]
Diving deeper, I checked out the code of other terminal based mail clients and first thought starting the editor through a sub-shell must be it. I used a small reproducer and can rule out that the sub-shell would do any terminal setting/clean ups.

That left me with the framework to do any terminal work. I dived into [https://github.com/urwid/urwid](urwid)s source code and found that urwid is handling the terminal in cases of stopping/starting (see https://github.com/urwid/urwid/blob/master/urwid/display_common.py#L735) . I'll check out brick/vty whether it can handle term changes and prepare a patch in case it doesn't (or it doesn't work properly).

**Comment by jtdaugherty** [comment]
Interestingly, if I run `stty`, `vim`, `kill`, and then `stty`, the terminal state is no different. Maybe it depends on how `vim` is killed; or maybe it depends on other factors like the version of `vim` in use (in my test I used `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  3 2019 04:38:39)`).
