### ISSUE TITLE
Generic build instructions

### ISSUE THREAD

**Issue by hughwilliams94** [purebred-mua/purebred#352]
Would it be possible to provide some straightforward build instructions for user that are not using Fedora or the Nix package manager. I tried to look through Travis config and run the cabal commands manually, but always encountered problems on Arch Linux.

**Comment by romanofski** [comment]
Hi @hughwilliams94 ,

I think that's a great idea. I think our HACKING document provides insights in how to setup a development environment, but is perhaps not as obvious as our README on the front of the repository?

**Comment by frasertweedale** [comment]
On Thu, Dec 12, 2019 at 04:24:54PM -0800, Roman Joost wrote:
> Hi @hughwilliams94 ,
> 
> I think that's a great idea. I think our HACKING document provides insights in how to setup a development environment, but is perhaps not as obvious as our README on the front of the repository?
> 
Maybe a link to HACKING from README will suffice (plus whatever
updates we might need to make to HACKING)?

**Comment by hughwilliams94** [comment]
I did have a look at the HACKING document, but again the instructions are for using Nix. I do agree it should probably be linked from the readme though.

**Comment by romanofski** [comment]
The thing with linking it from the README is that I think no one actually notices it. Reason that I believe that it's not obvious is because we already link to the HACKING document.

Perhaps the better place (I thought at least) would be below the repositories/instructions for Fedora/Nix ?

**Comment by romanofski** [comment]
@hughwilliams94 Btw. if there are any specific problems you're hitting when you've tried to build purebred I'd be interested to know about them too. Can't hurt to know what people try and what they're running into especially on platforms we don't use.

**Comment by romanofski** [comment]
@hughwilliams94 would you mind giving the instructions added in #353 a crack? I'd be interested whether these are enough to help you get going.

**Comment by hughwilliams94** [comment]
Hi thanks for updating the page. I had a go but I have been getting endless dependency errors from `cabal`. I think it may well be linked to this point in the [Arch Wiki](https://wiki.archlinux.org/index.php/haskell#Problems_with_linking). I don't have any idea how the haskell packaging ecosystem works, but I tried the recommendations in that link and nothing seems to help.

**Comment by hughwilliams94** [comment]
Reading up a little it seems that Haskell is a bit messed up on Arch, I have decided to remove all of the system packages and try to go down the `stack` route to see whether the situation improves.

**Comment by hughwilliams94** [comment]
Switching to `stack` and then installing `cabal` allowed me to get these instructions to work. Purebred seems great! I suppose the best way to adapt the readme might be to add a link to this issue so that any other Arch user can try my workaround if they want too. Just for clarity's sake, I found the recommendation to switch to `stack` in this [reddit post](https://www.reddit.com/r/archlinux/comments/7hanz7/whats_the_current_state_of_haskell_on_arch/dqpk93j/?context=8&depth=9).
