### ISSUE TITLE
Investigate: Colour handling in our acceptance tests

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#381]
**Is your feature request related to a problem? Please describe.**
I have the slight suspicion that our `TERM=ansi` setting is not having the effect of isolation we think it will have.

First of all, I've ran into different behaviour between travis and my local sandbox when it came to my local test implementing #5. The test:

```Haskell
testBulkActionsOnThreadsByKeybinding :: PurebredTestCase
testBulkActionsOnThreadsByKeybinding =
  purebredTmuxSession "perform bulk labeling on threads by keybinding" $
  \step -> do
    startApplication

    step "Toggle thread and list cursor moves to next list item"
    sendKeys "*" (Substring "Marked: 1")
      >>= assertRegex (
        -- toggled
        buildAnsiRegex ["7"] ["34"] ["43"] <> "\\sAug'17.*whitespace in the subject\\s+\n"
        -- current selection
        <> buildAnsiRegex ["0"] ["34"] ["43"] <> "\\sAug'17 rjoost@url.use.*This is Purebred\\s+\n"
        -- unselected rest
        <> buildAnsiRegex [] ["37"] ["49"] <> "\\sFeb'17.*WIP Refactor"
      )

    step "Toggle thread and list cursor moves to next list item"
    sendKeys "*" (Substring "Marked: 2")

    step "Tag toggled list items using key binding"
    sendKeys "a" (Substring "New: 3  ]")
      -- untoggled
      >>= assertRegex (buildAnsiRegex [] ["37"] [] <> "\\sAug'17.*whitespace in the subject\\s+\n")
```
and the failure 
[in log.txt](https://github.com/purebred-mua/purebred/files/4440901/log.txt)
shows that the current selection does not set any foreground and background colour attributes. Locally it does however. So where does the difference in behavior come from.

Secondly, reading up on [colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) in ANSI escape sequences and several comments on the interwebs suggests that `TERM=ansi` might not understand colour at all. Instead `xterm`, `linux` or simply `tmux` might be the better setting. Perhaps it would be good to check what type of colour depth `ansi` really supports.

Thirdly, colour support in [vty](https://hackage.haskell.org/package/vty-5.28.2/docs/Graphics-Vty-Attributes-Color.html#t:Color) has it's own limitations. Perhaps here it would be good to check whether `Term=ansi` does the right thing or not. 

**Describe the solution you'd like**
A better understanding where the color support comes from and how our setting `TERM=ansi` provides the desired isolation from random side effects or not.

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot_2020-04-07 Job #1566 1 - purebred-mua purebred - Travis CI](https://user-images.githubusercontent.com/121047/78608111-a2874d80-78a3-11ea-8105-a0981707859b.png)

**Comment by frasertweedale** [comment]
Looking at the raw data, maybe it's another variation on how escape sequences are generated.  What are the exact versions of tmux, brick and vty involved?

**Comment by frasertweedale** [comment]
@romanofski tried with vty-5.28.2 on your local machine yet?

**Comment by romanofski** [comment]
Hm.. yes why have I not thought about that in the first place. So I've put the snipped back in, removed the failing test which was now obsolete due to refactoring and it seems it has something to do with different set of versions: https://travis-ci.org/github/purebred-mua/purebred/builds/671935149?utm_medium=notification&utm_source=github_status

The nix build passes since it's versions are pinned (uses vty-2.25) while the others fail use (vty-2.58). I'll re-run the nix build and see what's up.

**Comment by romanofski** [comment]
Seems like vty-5.28 depends on ansi-terminal with the upgrade for better unicode support. I tried to use the newer vty version in Nix, but ansi-terminal also comes with additional dependencies. I've pushed an additional commit to pin vty to a lower version than 5.28 and I thought better wait until more platforms have the newer version.

I could also upgrade the NixOS release to an unstable release. It'll probably bring a new compiler release with it too. Currently not in the mood for the hassle.

**Comment by romanofski** [comment]
Alright I'll take back my last comment. The problem already exists in 5.27. Will investigate further...

**Comment by frasertweedale** [comment]
The version of tmux in CI seems really old too.  (v2.1).  Wonder if there's a way to test with newer tmux, maybe via a ppa?

**Comment by romanofski** [comment]
Hm.. that's a good idea, however I just saw your 2.7 version fail. Made me look into what the nix environment is using, which is `2.9a`.

**Comment by romanofski** [comment]
Hrmpf.. I guess `Ubuntu 16.04.6 LTS` itself is old as ... which makes it even trickier to find ppa's for.

**Comment by frasertweedale** [comment]
@romanofski haven't successfully installed tmux-2.7 yet; failing at the PPA setup :)

**Comment by romanofski** [comment]
I guess something must have happened between tmux release 2.1 and tmux 2.7 which had finally fixed it. Perhaps leave this card open as an investigation in order to find what it was, what caused the difference in test outcomes?

**Comment by frasertweedale** [comment]
The issue went away with a tmux upgrade.  We left this ticket open to investigate, but >1 year has passed so I'm just going to close this.

**Comment by romanofski** [comment]
Haha fair enough.
