### ISSUE TITLE
New mail notification

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#4]
Not sure if that really needs an issue since it feels so basic.

**Comment by frasertweedale** [comment]
Yeah we should track baseline features.  As discussed elsewhere make a milestone "0.1" or whatever you want to call it and put all features deemed essential in there.

**Comment by frasertweedale** [comment]
OK is it time to revisit this?  I propose two stages:

1. an action to repeat the current search and update view
2. add configuration to do that automatically, at a configured interval

**Comment by romanofski** [comment]
For 1) should be an easy fix since the current search is persisted in the search editor ... I'm a bit fuzzy for 2) since I would think it might involve IO? Nevertheless it might be good to split this up into two smaller sub tasks ...

**Comment by romanofski** [comment]
From IRC:

> 2019-07-31 14:13:28_frase_romanofski: ok, I was a bit concerned about new mail notification and doing searches in background, etc.  But I just thought about it: timer (or also, user action) can enqueue and event for main Brick event loop to process.  In event handler, if we are in an appropriate UI state, run the search, compare, set notification

**Comment by romanofski** [comment]
This was actually implemented and fixed by #323
