### ISSUE TITLE
module hierarchy cleanup

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#416]
I would like to tidy up the module hierarchy, including:

- [x] `Types` -> `Purebred.Types[.Foo]`
- [x] `Error` -> `Purebred.Types.Error`
- [x] `Storage.*` -> `Purebred.Storage.*`
- [x] `UI.*` -> `Purebred.UI.*`
- [x] `Config.Main` -> `Purebred.Config`
- [x] `Brick.Widgets.StatefulEdit` -> `Purebred.UI.Widgets` (maybe, or something similar)
- [x] drive-by license and copyright comments on files touched

@romanofski let me know what you think.

**Comment by romanofski** [comment]
Sounds pretty good to me!!

**Comment by frasertweedale** [comment]
@romanofski you got any big changes brewing?  I don't want to inconvenience you with merge conflicts :)

**Comment by romanofski** [comment]
Hm.. nah not really. The Haskeline stuff at the moment I can easily move around...

**Comment by frasertweedale** [comment]
All tasks done.
