### ISSUE TITLE
Mail is still `sent` even if an error occurs

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#418]
**Describe the bug**
When an error occurs in the sendmail function, the error is displayed alright, but the mail is still shuffled away into the `Sent` folder while I find myself back at the index view.

**To Reproduce**
1. Change the path in the `_cvSendMailCmd` to something bogus so it errors
2. Compose a mail and press send
3. The mail is indexed and created in the `Sent` folder, but it obviously hasn't been sent at all

**Expected behavior**
I remain on the composition view and the error is displayed.

**Screenshots**
Easy to reproduce.

**Additional context**
I presume the current pass is like the quickest hack we were able to get away with, but it's obviously not really good.

**Comment by frasertweedale** [comment]
Yeah, we need to handle this better.  Thanks for filing the ticket.

**Comment by frasertweedale** [comment]
I'll take this one.
