### ISSUE TITLE
different actions for new search / refine search

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#435]
**Describe the solution you'd like**
As a user, I sometimes wish to refine the current search, and sometimes wish to start a new search.
The current search behaviour places the cursor at the end of the current search term.  So when conducting
a new search, the original term must first be deleted.

Therefore, I would like separate actions for *refine search* (current behaviour) and *new search*
(start with an empty string).  These can be be wired to different keybindings.

**Describe alternatives you've considered**
Status quo: making my backspace finger swol.

**Comment by romanofski** [comment]
Hm... instead of using Backspace, use `CTRL+u` to start from scratch. With that in mind, is there still a need for this?

**Comment by frasertweedale** [comment]
Yeah I guess I just don't know the keybindings... haskeline support would be ideal :)
