### ISSUE TITLE
Keybinding to show all header in an e-mail

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#44]
When viewing an e-mail, it should be possible to see all headers of the e-mail. That will help with picking header fields to filter on as implemented in #25 .

**Comment by frasertweedale** [comment]
How this should work:

1. The view should have a configuration slot of type `(CI B.ByteString -> Bool)`.  This predicate is
    evaluated for each header and tell the view whether to show it or not.

2. The keybinding should just set this config to `const True`.

3. If you want a "toggle" action, then we'll need some state in the view that is readable (and
    writable / influenceable) by the key action.  But in the simple case you could have two
    key bindings - one for "show all headers" and the other for "show *default* headers"

**Comment by romanofski** [comment]
I like the idea. I'll try it out.

**Comment by romanofski** [comment]
Hm... so.. I've got it implemented over here: 8ad3b74d072c9928c8f6a81de8b7f5c4b7ca2e86 with a few adjustments due to the current mail parser. I'm using a keybinding which toggles with an additional type keeping the state.
I'm not sure about the benefit of using a function as the configuration slot, apart from maybe in a case you really have some weird choices to make when filtering - what do I know. Apart from that wouldn't it most often just be: "do I want to see this header? no - ignore it"?

In regards to your second point: this would only work with number 3 or keeping track of the state, wouldn't it? Otherwise once you press the keybinding to set: const True in the configuration you don't have access to to what the user had configured. Hm.. unless I've missed something.

Have a look if you've got time :)

**Comment by frasertweedale** [comment]
I like how you did the toggle.

**Comment by romanofski** [comment]
Cheers! Closing this :)
