### ISSUE TITLE
mail view: search within body does not scroll to search term

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#448]
**Describe the bug**

When viewing a mail, searching for a term within the body of a mail, where that term appears multiple times,
scrolls down 1 line each time when calling the "next" occurrence.

**Expected behavior**
Viewport should scroll to put the "next" occurrence of the search term in view.

**Comment by romanofski** [comment]
I'll keep it with in the 1.0 release. Since shipping a b0rked search would be confusing and diminish the usefulness.

**Comment by frasertweedale** [comment]
Assigning to me; I have a fix.
