### ISSUE TITLE
merge purebred-dump-keybinding into main program

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#450]
**Is your feature request related to a problem? Please describe.**

The `purebred-dump-keybindings` program involves considerable complexity to initialise the configuration, which is mostly duplicating the main program itself.  But there is an important difference: `purebred-dump-keybindings` does not load user configuration or run config plugin hooks that could result in customised keybindings.  So it can only show the default keybindings.

**Describe the solution you'd like**
Merge this "dump keybindings" behaviour into the main program, triggered by the `--dump-keybindings` flag

**Describe alternatives you've considered**
nil

**Additional context**
This also has the nice effect of having fewer programs to update when API changes, and the `exe:purebred-dump-keybindings` build target will be no more (so it cannot be missed accidentally).

**Comment by frasertweedale** [comment]
@romanofski what do you think?

**Comment by romanofski** [comment]
Yeah sounds good to me. Especially avoiding duplication.

**Comment by frasertweedale** [comment]
OK, I'll probably do it in the next day or so (only came up due to another refactor in progress).
