### ISSUE TITLE
migrate to brick-1.0

### ISSUE THREAD

**Issue by jtdaugherty** [purebred-mua/purebred#464]
I'm working on an overhaul of `brick`'s `EventM` API and I'd love to get your feedback on how it might impact this project. Please see the details and post comments on https://github.com/jtdaugherty/brick/issues/379. Thanks!

**Comment by romanofski** [comment]
Hi @jtdaugherty thanks for letting us know. We only had a quick glimpse and it looks like it would make things easier. I'll see if I can get some time to work against your branch to see what would change.

Generally speaking tho, I think we would just adapt. What do you think @frasertweedale ?

**Comment by frasertweedale** [comment]
The change is going ahead and will be released in brick-1.0.  See https://github.com/jtdaugherty/brick/issues/379#issuecomment-1203390245.

Therefore, morphing this ticket into a "migrate to brick-1.0" task.

**Comment by jtdaugherty** [comment]
Hi, folks - Brick 1.0 is out. Here are the details: https://github.com/jtdaugherty/brick/blob/master/CHANGELOG.md#10

**Comment by frasertweedale** [comment]
Thanks @jtdaugherty.  Congrats on the milestone release and thanks for your continuing work on *brick* and *vty*, for which we are enduringly grateful!

**Comment by jtdaugherty** [comment]
Thank you, I'm glad to hear it!

**Comment by frasertweedale** [comment]
@romanofsk fyi I've started work on the migration.
