### ISSUE TITLE
crash in `setupTerm` when initial search term has huge result set

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#49]
When the initial search term returns a large number of messages,
purebred crunches away at it.  The UI does not get drawn and after
a few seconds the program crashes with message:

    custom.hs: setupTerm: Couldn't look up terminfo entry "xterm-256color"

**Comment by romanofski** [comment]
Yeah wonder if it's related to #51 or if it's a separate issue. It should at least start, even tho taking ages.

**Comment by romanofski** [comment]
aah this is an interesting one... I've dabbled a bit and what I found was:

  open("/usr/share/terminfo/s/screen-256color", O_RDONLY) = -1 EMFILE (Too many open files)

which sounds very familiar. We're currently using 05272915f19320362d3a2eb2ffc80eacd7162b7a of hs-notmuch, perhaps I should upgrade?

**Comment by frasertweedale** [comment]
@romanofski nah, just make sure you're not accessing the "To" header.  Also, are you parsing the mail file(s) at all?

**Comment by romanofski** [comment]
Not paying the mail files, but an unindexed field. Now I remember. Will check :-)
