### ISSUE TITLE
tag replacement in thread and mail list

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#492]
**Is your feature request related to a problem? Please describe.**

Tags (e.g. `inbox`, `replied`, `attachment`, `flagged`, etc) take up significant horizontal space in the Thread and Mail list.

**Describe the solution you'd like**

I would like a (customisable) facility to replace particular tags with a shorter string e.g. a single char or emoji.  For example, `replied` replaced with ↩️, `attachment` with 📎, and so on.  A replacement must allow more than 1 `Char`, to allow for combining/modifier codepoints.  We can ship with a default set or maybe two (one ASCII, one emoji) of replacements for [special tags](https://notmuchmail.org/special-tags/).

**Describe alternatives you've considered**
Do nothing and put up with loss of horizontal space for actual subject.

**Comment by romanofski** [comment]
Yeah I've seen those translations happen in other editors. I wonder if a naive implementation is just a map we can look up the icons for each tag. Could perhaps be stored in the Config?

**Comment by frasertweedale** [comment]
@romanofski I already have a branch.  Will push it soon.
