### ISSUE TITLE
Marking in order to perform bulk actions

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#5]
I use tagging to perform actions on multiple mails every day.

**Comment by frasertweedale** [comment]
Is this kind of tagging different from the "categorisation" tagging?  Or a special case thereof?

**Comment by romanofski** [comment]
Yes it's different from categorisation. Basically this type of tagging can also be described of marking several mails in order to perform a bulk action on them.

**Comment by frasertweedale** [comment]
On Tue, Jul 18, 2017 at 05:43:21PM -0700, Roman Joost wrote:
> Yes it's different from categorisation.
> 
So we have a terminology overload.  No worries, let's use 'marking'
and 'tagging' to refer to the separate concepts going forward.

**Comment by romanofski** [comment]
I actually grabbed this one since I do this quite often if I got a bunch of automatically generated mails from Gitlab or Jira and don't want to deal with every single one of them.

**Comment by romanofski** [comment]
@frasertweedale just ran into this one:

```Haskell
-- i is the index returned by view (asMailIndex . miListOfThreads . L.listSelectedL) s
(\i -> pure $ over (asMailIndex . miListOfThreads . L.listElementsL . coerced . _) not s)
```

but since the type of `miListOfThreads` is `ListWithLength V (SelectableItem NotmuchThread)` and:

```Haskell
newtype V a = V [V.Vector a]
  deriving (Functor, Foldable, Traversable, Show)

```
I have trouble indexing the lazy vector. I have two questions:

1. Do you think we could find an index "lazily" without evaluating the entire list?
1. if yes to the former I suppose we could write an [Index](http://hackage.haskell.org/package/lens-4.17/docs/Control-Lens-At.html#t:Index) instance and I can carry on?

**Comment by frasertweedale** [comment]
What do you mean by "find an index"?  Do you mean to walk the list until an element satisfying a particular condition is encountered?

**Comment by romanofski** [comment]
The problem I have is that I can't use the `ix` lens on the generic brick list using the lazy vector. I thought that is due to the data type being a `newtype` which uses a vector of chunks. Naturally I was wondering how that would be indexable in the sense that you have a list item `n` and the list can tell you it's index `i` in that lazy loaded list (in this example retrieved by `L.listSelectedL`). Does that explain it?

**Comment by frasertweedale** [comment]
OK so you want `instance Ix (V a)`?  It might be possible, I'll investigate later this week.

**Comment by frasertweedale** [comment]
@romanofski see PR #363

**Comment by romanofski** [comment]
I've made some progress with this. Currently I've done a bit of refactoring, but there is more to come. Basically that I can manage (tag) operations on a bunch of threads instead of just the selected one. I think I'll push a bit further and see if this can be abstracted so that we can at least do tag operations on any selected item which would give us batch operations on threads and mails. 

Perhaps we could push even further and define bulk actions on lists with more than one selected item ...

**Comment by romanofski** [comment]
Had a quick chat to Fraser on IRC and we came to the conclusion that we want a separate utility function following similar implementation style like `HasList`. The implementation should be a subclass of `HasList`. It's all a bit vague I know.. just have to see how well it works out.

**Comment by romanofski** [comment]
I've made some progress today. One thing I've realized is that tracking the toggled/selected state of an item or items outside of Brick is cumbersome. At the moment we keep the toggled state in the list item with:

```Haskell
type SelectableItem a = (Bool, a)
```
That works fine for all items I want to use for batch actions. Sometimes however I only want to apply things to a single element. Now getting a list of __either__ selected or toggled items is the tricky bit. E.g. I've tried:

```Haskell
let selected = toListOf (asMailIndex . miListOfThreads . traversed . filtered fst) s
     curSel = toListOf (asMailIndex . miListOfThreads . to L.listSelectedElement . traversed . _2) s
manageThreadTags ops (selected <|> curSel)
```

but that could mean worse case that I tag the same selected *and* toggled list item twice.

The other bit is, that Brick already provides functions to update the selected elements with an action. If I pull the elements (either selected, or toggled) out of the list, I need to figure out the same way how to write them back in. Pulling out a list of items is one thing, but updating those items again in the list is another.

**Comment by romanofski** [comment]
@frasertweedale I've got to ask for a bit of help. I've got the functionality so far as I wanted (with a few inconsistencies). However I struggle a bit with the type families. For example, to simplify the `untoggleListItems` function (I've pushed my current WIP [here](https://github.com/purebred-mua/purebred/blob/feature/5-marking-for-bulk-actions/src/UI/Actions.hs#L1189) I started of changing it to use the generic `list` like so:

```Haskell
untoggleListItems :: forall v ctx. HasSelectableItemList ctx => Action v ctx ()
untoggleListItems =
    Action
    { _aDescription = ["untoggle all selected list items"]
    , _aAction = modifying (list (Proxy @ctx) . traverse . filtered fst) (\m -> set _1 False m)
    }
```
However the compiler disagrees with:
```
src/UI/Actions.hs:1193:29-45: error:
    • Couldn't match type ‘E ctx’ with ‘(Bool, b0)’
      Expected type: (L.GenericList Name (T ctx) (Bool, b0)
                      -> Identity (L.GenericList Name (T ctx) (Bool, b0)))
                     -> AppState -> Identity AppState
        Actual type: (L.GenericList Name (T ctx) (E ctx)
                      -> Identity (L.GenericList Name (T ctx) (E ctx)))
                     -> AppState -> Identity AppState
      The type variable ‘b0’ is ambiguous
    • In the first argument of ‘(.)’, namely ‘list (Proxy @ctx)’
      In the first argument of ‘modifying’, namely
        ‘(list (Proxy @ctx) . traverse . filtered fst)’
      In the ‘_aAction’ field of a record
    • Relevant bindings include
        untoggleListItems :: Action v ctx ()
          (bound at src/UI/Actions.hs:1190:1)
     |
1193 |     , _aAction = modifying (list (Proxy @ctx) . traverse . filtered fst) (\m -> set _1 False m)
     |                             ^^^^^^^^^^^^^^^^^

```

I'm don't understand why it's actual type is `(L.GenericList Name (T ctx) (E ctx)` instead of the expected `(L.GenericList Name (T ctx) (Bool, b0)`. Any chance I can make it less ambiguous?

**Comment by romanofski** [comment]
I "think" that have made some progress, but I've hit a wall again. I think that I need a [Lens](http://hackage.haskell.org/package/lens-4.17/docs/Control-Lens-Lens.html#t:Lens) for https://github.com/purebred-mua/purebred/commit/5b98521d300a6b447ba8a6f9c00c48861c780577#diff-17fe81b31dc7d22a8f09101721b8242dR303 but defining a simple lens is stops with a compiler message:

```
-- selectedItemsL :: Proxy n -> Lens' AppState (E n)
• Could not deduce (Applicative f)
        arising from a use of ‘traversed’
```
which makes me wonder how to define it. Using a traversal, I get:

```
• Could not deduce (Control.Lens.Tuple.Field1
                          (E ctx) (E ctx) a0 Bool)
        arising from a use of ‘_1’
```
