### ISSUE TITLE
Proper error propagation: Use MonadError transformer

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#57]
With the implementation to automatically set mails as "read" I ran into one case in which I had a hard time properly propagating the error up to the application out of function with IO. Consider cleaning this up by using the MonadError transformer.

For the discussion see #56

**Comment by frasertweedale** [comment]
@romanofski
See commit purebred-mua/hs-notmuch@5bc75a6344163899d09153bb9e08bc620ee343ee
(on master branch)

**Comment by romanofski** [comment]
I think we can also close this one, since this ticket targeted mostly error propagation between hs-notmuch and purebred.
