### ISSUE TITLE
Mail: Adding/Removing tags

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#65]
This feature is to add/remove tags for an individual e-mail. We've got most of the infrastructure there, so implementing this shouldn't be much work anymore. UI wise, I would go with a simple input which can later be extended to autocompletion and color coding and whatever. But to keep it simple for now, using prefixes like e.g. `+tag` and `-tag` to indicate adding and removing. That should work in the index and when viewing an e-mail.

**Comment by romanofski** [comment]
I want to jump on this again. I first had in mind to also implement some form of auto completion when typing, but I think I'll rather defer this.

Basically getting a line of `Text` I think what would make sense is to write a small parser which can transform e.g. `+foo -bar` into something like `[AddTag foo, RemoveTag bar]`? In a separate backlog item we then can color code maybe invalid tags and what not. Basically stuff which fails the parser.

**Comment by frasertweedale** [comment]
What's the advantage of `+` and `-` when we could just parse the exact list of tags wanted?

**Comment by romanofski** [comment]
The advantage would be to indicate what tags you want to add vs the ones you want to remove in a single line.

**Comment by frasertweedale** [comment]
/me shruggs.  I think it's overkill.  How many tags is a message likely to have?  Just as easy to
add,remove it from a comma/space separated list.

But hey if you want the `+`/`-` I'm not gonna fight you over it :)

**Comment by romanofski** [comment]
Hm... actually good point I haven't thought about. Comma separated list of tags might be a good start.

**Comment by romanofski** [comment]
Argh... now I fall flat on my face incorporating the idea we've discussed from gist: https://gist.github.com/frasertweedale/ca33db4aa71344124b65696c67835ca2 when I put the Keybindings into practice:

```Haskell
indexKeybindings :: [Keybinding 'BrowseMail (Brick.Next AppState)]
indexKeybindings =
    [ Keybinding (V.EvKey V.KEsc []) quit
    , Keybinding (V.EvKey (V.KChar ':') []) (focus `chain'` (continue :: Action 'SearchMail (Brick.Next AppState)))
```
which fails with:

```
/home/rjoost/works/purebred/src/UI/Index/Keybindings.hs:14:7: error:
    • Couldn't match type ‘'SearchMail’ with ‘'BrowseMail’
      Expected type: Keybinding 'BrowseMail (Brick.Next AppState)
        Actual type: Keybinding 'SearchMail (Brick.Next AppState)
    • In the expression:
        Keybinding
          (V.EvKey (V.KChar ':') [])
          (focus
           `chain'` (continue :: Action SearchMail (Brick.Next AppState)))
      In the expression:
        [Keybinding (V.EvKey V.KEsc []) quit,
         Keybinding
           (V.EvKey (V.KChar ':') [])
           (focus
            `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
         Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
         Keybinding (V.EvKey V.KDown []) (mailIndexDown `chain` continue),
         ....]
      In an equation for ‘indexKeybindings’:
          indexKeybindings
            = [Keybinding (V.EvKey V.KEsc []) quit,
               Keybinding
                 (V.EvKey (V.KChar ':') [])
                 (focus
                  `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
               Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
               ....]
```

Understandable, but two questions:

1. We've set it to 'BrowseMail for a purpose in order to typecheck the actions and to avoid that users register actions which are nonsense. Now we necessarily need to register actions which are of a different type rendering our initial idea ... void?

2. If we need to keep the context flexible for the Keybindings, I've tried that too, but run into a different TypeError:

```
    • Couldn't match type ‘ctx’ with ‘'BrowseMail’
      ‘ctx’ is a rigid type variable bound by
        the type signature for:
          indexKeybindings :: forall (ctx :: Mode).
                              [Keybinding ctx (Brick.Next AppState)]
        at src/UI/Index/Keybindings.hs:11:21
      Expected type: Keybinding ctx (Brick.Next AppState)
        Actual type: Keybinding 'BrowseMail (Brick.Next AppState)
    • In the expression:
        Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue)
      In the expression:
        [Keybinding (V.EvKey V.KEsc []) quit,
         Keybinding
           (V.EvKey (V.KChar ':') [])
           (focus
            `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
         Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
         Keybinding (V.EvKey V.KDown []) (mailIndexDown `chain` continue),
         ....]
      In an equation for ‘indexKeybindings’:
          indexKeybindings
            = [Keybinding (V.EvKey V.KEsc []) quit,
               Keybinding
                 (V.EvKey (V.KChar ':') [])
                 (focus
                  `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
               Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
               ....]
    • Relevant bindings include
        indexKeybindings :: [Keybinding ctx (Brick.Next AppState)]
          (bound at src/UI/Index/Keybindings.hs:12:1)
```
I'm actually too tired today to think straight, so I'll defer till tomorrow. If something jumps out however. Let me know if anything jumps out. WIP is in 7b209ad016eb8996498194b6be493ea77d9edf83 in case it helps.

**Comment by frasertweedale** [comment]
On Thu, Oct 19, 2017 at 04:39:29AM -0700, Roman Joost wrote:
> Argh... now I fall flat on my face incorporating the idea we've discussed from gist: https://gist.github.com/frasertweedale/ca33db4aa71344124b65696c67835ca2 when I put the Keybindings into practice:
> 
> ```Haskell
> indexKeybindings :: [Keybinding 'BrowseMail (Brick.Next AppState)]
> indexKeybindings =
>     [ Keybinding (V.EvKey V.KEsc []) quit
>     , Keybinding (V.EvKey (V.KChar ':') []) (focus `chain'` (continue :: Action 'SearchMail (Brick.Next AppState)))
> ```
> which fails with:
> 
> ```
> /home/rjoost/works/purebred/src/UI/Index/Keybindings.hs:14:7: error:
>     • Couldn't match type ‘'SearchMail’ with ‘'BrowseMail’
>       Expected type: Keybinding 'BrowseMail (Brick.Next AppState)
>         Actual type: Keybinding 'SearchMail (Brick.Next AppState)
>     • In the expression:
>         Keybinding
>           (V.EvKey (V.KChar ':') [])
>           (focus
>            `chain'` (continue :: Action SearchMail (Brick.Next AppState)))
>       In the expression:
>         [Keybinding (V.EvKey V.KEsc []) quit,
>          Keybinding
>            (V.EvKey (V.KChar ':') [])
>            (focus
>             `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
>          Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
>          Keybinding (V.EvKey V.KDown []) (mailIndexDown `chain` continue),
>          ....]
>       In an equation for ‘indexKeybindings’:
>           indexKeybindings
>             = [Keybinding (V.EvKey V.KEsc []) quit,
>                Keybinding
>                  (V.EvKey (V.KChar ':') [])
>                  (focus
>                   `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
>                Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
>                ....]
> ```
> 
> Understandable, but two questions:
> 
> 1. We've set it to 'BrowseMail for a purpose in order to typecheck the actions and to avoid that users register actions which are nonsense. Now we necessarily need to register actions which are of a different type rendering our initial idea ... void?
> 
> 2. If we need to keep the context flexible for the Keybindings, I've tried that too, but run into a different TypeError:
> 
> ```
>     • Couldn't match type ‘ctx’ with ‘'BrowseMail’
>       ‘ctx’ is a rigid type variable bound by
>         the type signature for:
>           indexKeybindings :: forall (ctx :: Mode).
>                               [Keybinding ctx (Brick.Next AppState)]
>         at src/UI/Index/Keybindings.hs:11:21
>       Expected type: Keybinding ctx (Brick.Next AppState)
>         Actual type: Keybinding 'BrowseMail (Brick.Next AppState)
>     • In the expression:
>         Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue)
>       In the expression:
>         [Keybinding (V.EvKey V.KEsc []) quit,
>          Keybinding
>            (V.EvKey (V.KChar ':') [])
>            (focus
>             `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
>          Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
>          Keybinding (V.EvKey V.KDown []) (mailIndexDown `chain` continue),
>          ....]
>       In an equation for ‘indexKeybindings’:
>           indexKeybindings
>             = [Keybinding (V.EvKey V.KEsc []) quit,
>                Keybinding
>                  (V.EvKey (V.KChar ':') [])
>                  (focus
>                   `chain'` (continue :: Action SearchMail (Brick.Next AppState))),
>                Keybinding (V.EvKey V.KEnter []) (displayMail `chain` continue),
>                ....]
>     • Relevant bindings include
>         indexKeybindings :: [Keybinding ctx (Brick.Next AppState)]
>           (bound at src/UI/Index/Keybindings.hs:12:1)
> ```
> I'm actually too tired today to think straight, so I'll defer till tomorrow. If something jumps out however. Let me know if anything jumps out. WIP is in 7b209ad016eb8996498194b6be493ea77d9edf83 in case it helps.
> 
We'll fix this tomorrow morning.

**Comment by romanofski** [comment]
On a second thought the problem might not actually be a problem. Saying that we might want to separate the key bindings for managing tags from altering the search. So I try that approach first...

**Comment by romanofski** [comment]
Cool. Just realising that I had never send my initial comment. Happened a few times already. So, the following comes before my second thought:

There is a tricky bit with the abstraction we have at the moment and I'm not sure how it should play out with our configuration.

In the `Types.hs` we define:

```Haskell
data IndexViewSettings = IndexViewSettings
    { _ivKeybindings       :: [Keybinding 'BrowseMail (Next AppState)]
    , _ivSearchKeybindings :: [Keybinding 'SearchMail (Next AppState)]
    }
```
What I need for the `_ivSearchKeybindings` however is:

```Haskell
indexsearchKeybindings :: (Completable m) => [Keybinding m (Brick.Next AppState)]
```
Because I've defined a few instances for `Completable`. In particular applying the search results and the setting the tags. It builds at the moment, but because of the specific types set in `Types.hs` it always "defaults" to a search result instead of e.g. setting the tags.

I've tried to abstract these Keybindings in `Types.hs` as well, since these Keybindings could be used everywhere else. However I've ended up adding new type variables(?) all the way down to Configuration specifying the Kind of `Mode`.

Is that the only solution? Not sure how I would end up with our type alias:

```Haskell
type UserConfiguration = Configuration (IO FilePath) (IO String)
type InternalConfiguration = Configuration FilePath String
```

**Comment by romanofski** [comment]
Alright pushed 1f176875795e195c353f240062f4ed81fd0f1532 which "works", but isn't there yet. The shelving and restoring of the editor values can be done better, but I think I don't want to expose that detail as a Keyboard action. Need to think what's the best way to "hide" it.
