### ISSUE TITLE
add license blurb to files

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/purebred#69]
source files should have a license blurb in them, 

```
-- This file is part of purebred
-- Copyright (C) 2017  {{Fraser Tweedale and/or Roman Joost}}
--
-- purebred is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

I'll get around to this; just making a note so I don't forget :)

**Comment by romanofski** [comment]
Yeah good idea!

**Comment by romanofski** [comment]
Btw. just realising in regards to the author. I'd be in favor of Fraser and Roman for the authorship ... In the future it will go hopefully: and contributors ?

**Comment by frasertweedale** [comment]
Yeah just add author names to the copyright statement in each file where a substantive
contribution was made by each author.

**Comment by romanofski** [comment]
Just realising that github shows the author of the file, as well as it's contributors. Perhaps it's something to make use of?

**Comment by frasertweedale** [comment]
Well, so does git-blame.  We can automate it, but it's probably quicker to do it by hand :)
