### ISSUE TITLE
Consider listing purebred in the Brick featured projects list?

### ISSUE THREAD

**Issue by jtdaugherty** [purebred-mua/purebred#89]
I'm wondering if you would be interested in having `purebred` listed in the Brick README's featured projects list. If so, I'd be happy to add it and it would be very nice if you had a screenshot you could embed in your README!

**Comment by jtdaugherty** [comment]
(To wit: https://github.com/jtdaugherty/brick#featured-projects)

**Comment by frasertweedale** [comment]
@jtdaugherty by all means!  We are not yet "production ready" yet, but the exposure will be
appreciated.

Regarding screenshot, I filed a separate issue to track that:
https://github.com/purebred-mua/purebred/issues/90

Cheers!

**Comment by romanofski** [comment]
We just barely scraped past the 'Only-Vaporware' line :) PR #91 adds the screenshot.

**Comment by jtdaugherty** [comment]
I understand if you are concerned about visibility while things are still under heavy development, but it looks like you put a disclaimer in your README, too. So I'm happy to add `purebred` to the list.

https://github.com/jtdaugherty/brick/commit/159f9f706269ad64f4ffb20fdef3978772d87163

**Comment by frasertweedale** [comment]
Thanks @jtdaugherty!

**Comment by romanofski** [comment]
w00h00 \o/ cheers @jtdaugherty
