### ISSUE TITLE
Configure "Identities" to compose an email

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#93]
We need a way to configure multiple Identities in order to retrieve them when composing mail. This can be kept simple for the first release and only support one name and email.

**Comment by frasertweedale** [comment]
As in , the "from" address(es)?

**Comment by romanofski** [comment]
Yes. I remember I had once two, one for work and a private one. It came with different signatures now thinking of it.

**Comment by romanofski** [comment]
I thought about this. Perhaps for 1.0 we can stick with one identity. What needs to happen for multiple identities tho is a way to select them. I had a form of auto completion in mind, since we can re-use this for tagging. I can't see that any other items really, really need auto completion for now. So maybe we just stick with one sender address for now.

**Comment by romanofski** [comment]
Turns out, that configuring a list of `[Mailbox]` using `Data.MIME` is a piece of cake.
