### ISSUE TITLE
Action: Jump to next or previous unread

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred#94]
We need an Action which jumps to the next unread e-mail in the mail index. At the moment we only jump to the next item in the list which is not really helpful sometimes.

I think everything should be there to piece this together. Possibly just combinding [findIndex](https://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector.html#v:findIndex) with [listMoveTo](https://hackage.haskell.org/package/brick-0.20.1/docs/Brick-Widgets-List.html#v:listMoveTo) is all what needs to happen.

**Comment by frasertweedale** [comment]
Be aware that `findIndex` is *O(n)* in entire vector.  Better approach would be to search a tail
of the vector i.e.

1. let cur = the current index (I assume Brick can tell you that... `fst . listSelectedElement` ?)
2. let next = `findIndex f . drop (cur + 1) $ vec`
3. `listMoveTo next`

`drop` is *O(1)*, i.e. the search for "next unread" will start at the next index *after* the current mail.

**Comment by romanofski** [comment]
I've hacked on it but realised that a) the tests needs to be adjusted for this and b) I'd like to include the ability also set tags on mails when you view them. Since with this change, the next unread mail will be or should be opened automatically, I'd like to wide the approach here in order to also allow adding tags during viewing of mails.

I think that shouldn't be too hard since the drawing code to show mail contents already borrows from the list of mails.
